apiVersion: apps/v1
kind: Deployment
metadata:
  name: goapp-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: goapp-pod
  template:
    metadata:
      labels:
        app: goapp-pod
    spec:
      containers:
      - name: goapp-container
        image: ngostal/golang:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
